name: 'Terraform Destroy'

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # Set default working directory for all run steps
    
    env:
      AWS_REGION: 'eu-central-1'  # Change this to your desired region

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.7.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve 